import { mkdtempSync, mkdirSync, cpSync, writeFileSync, readFileSync, readdirSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export function runDemo({ empty = false } = {}) {
  const sandbox = mkdtempSync(join(tmpdir(), 'autobrief-demo-'));
  try {
    cpSync(join(root, 'digest.mjs'), join(sandbox, 'digest.mjs'));
    cpSync(join(root, 'lib'), join(sandbox, 'lib'), { recursive: true });
    const transcriptsBase = join(sandbox, 'fictional-input');
    const session = join(transcriptsBase, 'fictional-project', 'agent-transcripts', 'demo-session');
    mkdirSync(session, { recursive: true });
    const fixture = readFileSync(join(root, 'demo', 'fictional-session.jsonl'), 'utf8');
    if (!empty) writeFileSync(join(session, 'demo-session.jsonl'), fixture);
    const outputDir = join(sandbox, 'reports');
    writeFileSync(join(sandbox, 'config.json'), JSON.stringify({
      transcriptsBase, projects: ['fictional-project'], reports: { outputDir },
      persona: { name: 'Fictional Example', role: 'Product operations' },
      webex: { spaces: [] }, todo: { listName: 'Fictional tasks' }
    }));
    const stdout = execFileSync(process.execPath, [
      '--import', join(root, 'demo', 'block-network.mjs'),
      join(sandbox, 'digest.mjs'), '--mode=daily', '--dry-run'
    ], { encoding: 'utf8', env: { PATH: process.env.PATH || '', TZ: 'UTC' } });
    const daily = join(outputDir, 'daily');
    const files = existsSync(daily) ? readdirSync(daily).filter(f => f.endsWith('.md')) : [];
    return { report: files.map(f => readFileSync(join(daily, f), 'utf8')).join('\n'), reportCount: files.length,
      stdout: stdout.replaceAll(sandbox, '<isolated-demo>') };
  } finally {
    rmSync(sandbox, { recursive: true, force: true });
  }
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = runDemo();
  if (result.reportCount !== 1) throw new Error('Expected one fictional daily report');
  const header = '# AutoBrief: executed offline demonstration\n\nGenerated by the actual CLI dry-run path using [fictional input](fictional-session.jsonl). No model, Webex, Microsoft To Do, or Jira service was called.\n\nThe legacy heading below says “accomplished,” but these bullets are input requests copied by the dry-run formatter, not verified completed work. This demonstrates ingestion and report generation, not AI summarization quality.\n\n---\n\n';
  writeFileSync(join(root, 'demo', 'output.md'), header + result.report);
  process.stdout.write(result.stdout + '\nWrote demo/output.md (fictional data only).\n');
}
